---
openapi: '3.0.3'
info:
  version: 1.0.0
  title: Accept header
paths:
  /things:
    get:
      operationId: listThings
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
            application/xml:
              schema:
                type: object
                properties:
                  name:
                    type: string
        400:
          description: Bad request
          content:
            text/plain:
              schema:
                type: string
  /things/{id}:
    delete:
      operationId: deleteThing
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: No content
  /things/report:
    get:
      operationId: thingsReport
      responses:
        200:
          description: OK
          content:
            text/csv:
              schema:
                type: array
                items:
                  type: string
  /things/custom:
    get:
      operationId: customAccept
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: string
