import { ts } from '@openapi-generator-plus/template-utils'
import { DocumentContext } from './types'

export function licenseInfo(ctx: DocumentContext): string {
	const info = ctx.info
	return ts`/**
 * ${info.title}
 * ${info.description ?? ''}
 *
 * ${info.version ? `OpenAPI spec version: ${info.version}` : ''}
 * ${info.contact ? `Contact: ${info.contact.email}` : ''}
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */`
}
