openapi: 3.0.3
info:
  title: Constraints
  version: '1.0'
paths: {}
components:
  schemas:
    Constraints:
      type: object
      properties:
        fileSize:
          type: integer
          format: int64
          maximum: 9007199254740991
          minimum: 9007199254740990
        smallFileSize:
          type: integer
          format: int64
          maximum: 1
          minimum: 23
        decimalFileSize:
          type: number
          maximum: 9007199254740991
          minimum: 9007199254740990
        array:
          type: array
          minItems: 1
          maxItems: 2147483647
        string:
          type: string
          minLength: 1
          maxLength: 2147483647
          pattern: 'abc*'
