openapi: 3.0.3
info:
  title: Enums
  version: '1.0'
paths:
  /test1:
    get:
      parameters:
        - name: a
          in: query
          schema:
            enum:
              - first
              - empty
              - ''
            x-enum-descriptions:
              - "The first"
              - "The empty one"
              - "An empty one"
      responses:
        200:
          description: OK
