openapi: '3.1.0'
info:
  title: Oddities
  version: '1.0'
paths: {}
components:
  schemas:
    SomeRequest:
      type: object
      properties:
        derp-derp:
          type: string
    NullProperty:
      type: object
      properties:
        meNull:
          type: "null"
